### ISSUE TITLE
About section link to wrong Rocky Linux Docker Hub image version

### ISSUE THREAD

**Issue by fschndr** [geerlingguy/docker-rockylinux9-ansible#5]
Dear Jeff, the "About" section of this GitHub repo for the Rocky Linux 9 Dockerfile is linking to the Docker Hub entry for the Rocky Linux 8 image. 

![Screenshot 2024-10-30 at 12 19 39](https://github.com/user-attachments/assets/032e2b82-0e5d-4a5d-ad66-c394cc4aae43)

Best regards,
Fabian

**Comment by geerlingguy** [comment]
Oops! Sorry about that, just fixed it.
